name: Elixir

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [
          1.11.3
        ]
        otp: [
          23.2
          #, 22.3
        ]


    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      id: setup-beam
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Retrieve Mix Dependencies Cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
        # cache key is hierarchical: OS, otp-version, elixir-version, mix.lock
        key: ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        # restore keys are tried on cache misses, and only match the key prefix
        restore-keys: |
          ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-
          ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-
          ${{ runner.os }}-mix-

    - name: Install Dependencies
      run: mix deps.get

    - name: Run Tests
      run: mix test